eureka:
  client:
    service-url:
      defaultZone: http://193.112.46.15:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 193.112.46.15:${server.port}

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/loofer/config-repo
          search-paths: /**
      label: master
    inetutils:
      use-only-site-local-interfaces: false
  rabbitmq:
    host: 193.112.46.15
    port: 5672
    username: admin
    password: rabbitmq
#          username: loofer
#          password: 123456

#management:
#  endpoints:
#    web:
#      expose: "*"
server:
  port: 8771